DROP TABLE IF EXISTS sa_address;

CREATE TABLE sa_address
(
  ADDRESS_ID VARCHAR(4000),
  ADDRESS VARCHAR(4000),
  ADDRESS2 VARCHAR(4000),
  DISTRICT VARCHAR(4000),  
  CITY_ID VARCHAR(4000),
  POSTAL_CODE VARCHAR(4000),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE()
);