DROP TABLE IF EXISTS sa_stores;

CREATE TABLE sa_stores
(
  STORE_ID VARCHAR(4000),
  STORE_NAME VARCHAR(4000),
  STORE_TYPE_ID VARCHAR(4000),
  IS_PROCESSED VARCHAR(1),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE()
);

