DROP TABLE IF EXISTS sa_type_payments;

CREATE TABLE sa_type_payments
(
  TYPE_PAYMENT_ID VARCHAR(4000),
  TYPE_PAYMENT VARCHAR(4000),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE()
);