DROP TABLE IF EXISTS sa_customers_stock;

CREATE TABLE sa_customers_stock
(
  CUSTOMER_ID VARCHAR(4000),
  NAME_OF_ORGANIZATION VARCHAR(4000),
  HEAD_OF_ORGANIZATION VARCHAR(4000),
  EMAIL VARCHAR(4000),
  IBAN VARCHAR(4000),
  ADDRESS_ID VARCHAR(4000),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE()
);

GO

DROP TABLE IF EXISTS sa_transaction_stock;

CREATE TABLE sa_transaction_stock
(
  SALE_ID VARCHAR(4000),
  INVOICE VARCHAR(4000),
  STORE_ID VARCHAR(4000),
  QUANTITY VARCHAR(4000),
  PRICE VARCHAR(4000),
  CUSTOMER_ID VARCHAR(4000),
  INVOICE_DATE VARCHAR(4000),
  SALE_AMOUNT VARCHAR(4000),
  ADDRESS_ID VARCHAR(4000),
  EMPLOYEE_ID VARCHAR(4000),
  TYPE_PAYMENT_ID VARCHAR(4000),
  BOOK_ID VARCHAR(4000),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE()
);