DROP TABLE IF EXISTS sa_countries;

CREATE TABLE sa_countries
(
  COUNTRY_ID VARCHAR(4000),
  COUNTRY VARCHAR(4000),
  REGION_ID VARCHAR(4000),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE()
);