DROP TABLE IF EXISTS sa_customers_retail;

CREATE TABLE sa_customers_retail
(
  CUSTOMER_ID VARCHAR(4000),
  FIRST_NAME VARCHAR(4000),
  LAST_NAME VARCHAR(4000),
  GENDER VARCHAR(4000),
  DATE_OF_BIRTH VARCHAR(4000), 
  ADDRESS_ID VARCHAR(4000),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE()
);