CREATE MASTER KEY;

CREATE DATABASE SCOPED CREDENTIAL AzureBlobStorageCredentialETL
WITH IDENTITY = 'SHARED ACCESS SIGNATURE',
SECRET = '';


CREATE EXTERNAL DATA SOURCE AzureBlobStorageDataSourceETL
WITH
(
	TYPE = BLOB_STORAGE,
	LOCATION = 'https://adlstoragemev.blob.core.windows.net',
	CREDENTIAL = AzureBlobStorageCredentialETL
);

DROP TABLE IF EXISTS ext_transaction_stock;

CREATE TABLE ext_transaction_stock
(
  SALE_ID VARCHAR(4000),
  INVOICE VARCHAR(4000),  
  STORE_ID VARCHAR(4000),
  QUANTITY VARCHAR(4000),
  PRICE  VARCHAR(4000),
  CUSTOMER_ID VARCHAR(4000),  
  INVOICE_DATE VARCHAR(4000),
  SALE_AMOUNT VARCHAR(4000),
  ADDRESS_ID VARCHAR(4000),
  EMPLOYEE_ID VARCHAR(4000),
  type_payment_id VARCHAR(4000),
  BOOK_ID  VARCHAR(4000)
);

DROP TABLE IF EXISTS ext_stock_customers;

CREATE TABLE ext_stock_customers
(
  CUSTOMER_ID VARCHAR(4000),
  NAME_OF_ORGANIZATION VARCHAR(4000),
  HEAD_OF_ORGANIZATION VARCHAR(4000),
  EMAIL VARCHAR(4000),
  IBAN VARCHAR(4000),
  ADDRESS_ID VARCHAR(4000)
);

