DROP TABLE IF EXISTS sa_type_payments;

CREATE TABLE sa_type_payments
(
  TYPE_PAYMENT_ID VARCHAR(4000),
  TYPE_PAYMENT VARCHAR(4000),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE()
);

DROP TABLE IF EXISTS sa_type_stores;

CREATE TABLE sa_type_stores
(
  TYPE_STORE_ID VARCHAR(4000),
  TYPE_STORE VARCHAR(4000),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE()
);

DROP TABLE IF EXISTS sa_regions;

CREATE TABLE sa_regions
(
  REGION_ID VARCHAR(4000),
  REGION_NAME VARCHAR(4000),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE(),
);

DROP TABLE IF EXISTS sa_posts;

CREATE TABLE sa_posts
(
  POST_ID  VARCHAR(4000),
  POST_NAME  VARCHAR(4000),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE()
);

GO 

DROP TABLE IF EXISTS sa_stores;

CREATE TABLE sa_stores
(
  STORE_ID VARCHAR(4000),
  STORE_NAME VARCHAR(4000),
  STORE_TYPE_ID VARCHAR(4000),
  IS_CPROCESSED VARCHAR(1),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE()
);

GO

DROP TABLE IF EXISTS sa_countries;

CREATE TABLE sa_countries
(
  COUNTRY_ID VARCHAR(4000),
  COUNTRY VARCHAR(4000),
  REGION_ID VARCHAR(4000),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE()
);

GO

DROP TABLE IF EXISTS sa_cities;

CREATE TABLE sa_cities
(
  CITY_ID VARCHAR(4000),
  CITY VARCHAR(4000),
  COUNTRY_ID VARCHAR(4000),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE()
);

GO

DROP TABLE IF EXISTS sa_authors;

CREATE TABLE sa_authors
(
  AUTHOR_ID VARCHAR(4000),
  AUTHOR_NAME VARCHAR(4000),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE()
);

GO

DROP TABLE IF EXISTS sa_address;

CREATE TABLE sa_address
(
  ADDRESS_ID VARCHAR(4000),
  ADDRESS VARCHAR(4000),
  ADDRESS2 VARCHAR(4000),
  DISTRICT VARCHAR(4000),  
  CITY_ID VARCHAR(4000),
  POSTAL_CODE VARCHAR(4000),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE()
);

GO

DROP TABLE If EXISTS sa_books;

CREATE TABLE sa_books
(
  BOOK_ID VARCHAR(4000),
  ISBN VARCHAR(4000),
  PUBLISHER VARCHAR(4000),
  BOOK_TITLE VARCHAR(4000),
  BOOK_AUTHOR VARCHAR(4000),
  YEAR_OF_PUBLICATION VARCHAR(4000),
  AUTHOR_ID VARCHAR(4000),
  CATEGORY_ID VARCHAR(4000),
  CATEGORY VARCHAR(4000),
  SUB_CATEGORY_ID VARCHAR(4000),
  SUB_CATEGORY VARCHAR(4000),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE()
);

GO

DROP TABLE IF EXISTS sa_customers_retail;

CREATE TABLE sa_customers_retail
(
  CUSTOMER_ID VARCHAR(4000),
  FIRST_NAME VARCHAR(4000),
  LAST_NAME VARCHAR(4000),
  GENDER VARCHAR(4000),
  DATE_OF_BIRTH VARCHAR(4000), 
  ADDRESS_ID VARCHAR(4000),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE()
);

GO

DROP TABLE if EXISTS sa_employees;

CREATE TABLE sa_employees
(
  EMPLOYEE_ID VARCHAR(4000),
  FIRST_NAME VARCHAR(4000),
  LAST_NAME VARCHAR(4000),
  POST_ID VARCHAR(4000),
  STORE_ID VARCHAR(4000),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE()
);

GO

DROP TABLE IF EXISTS sa_transaction_retail;

CREATE TABLE sa_transaction_retail
(
  SALE_ID VARCHAR(4000),
  INVOICE VARCHAR(4000),
  STORE_ID VARCHAR(4000),
  QUANTITY VARCHAR(4000),
  PRICE VARCHAR(4000),
  CUSTOMER_ID VARCHAR(4000),
  INVOICE_DATE VARCHAR(4000),
  SALE_AMOUNT VARCHAR(4000),
  ADDRESS_ID VARCHAR(4000),
  EMPLOYEE_ID VARCHAR(4000),
  TYPE_PAYMENT_ID VARCHAR(4000),
  BOOK_ID VARCHAR(4000),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE()
);

GO

DROP TABLE IF EXISTS ext_type_stores;

CREATE TABLE ext_type_stores
(
  TYPE_STORE_ID VARCHAR(4000),
  TYPE_STORE VARCHAR(4000)  
);

DROP TABLE IF EXISTS ext_type_payments;

CREATE TABLE ext_type_payments
(
  TYPE_PAYMENT_ID VARCHAR(4000),
  TYPE_PAYMENT VARCHAR(4000) 
);

DROP TABLE IF EXISTS ext_stores;

CREATE TABLE ext_stores
(
  STORE_ID VARCHAR(4000),
  STORE_NAME VARCHAR(4000),
  STORE_TYPE_ID VARCHAR(4000)
);

DROP TABLE IF EXISTS ext_posts;

CREATE TABLE ext_posts
(
  POST_ID VARCHAR(4000),
  POST_NAME VARCHAR(4000)
);

DROP TABLE IF EXISTS ext_cities;

CREATE TABLE ext_cities
(
  CITY_ID  VARCHAR(4000),
  CITY VARCHAR(4000),
  COUNTRY_ID  VARCHAR(4000)
);

DROP TABLE IF EXISTS ext_regions;

CREATE TABLE ext_regions
(
  REGION_ID VARCHAR(4000),
  REGION_NAME VARCHAR(4000)
);

DROP TABLE IF EXISTS ext_country;

CREATE TABLE ext_country
(
  COUNTRY_ID VARCHAR(4000),
  COUNTRY VARCHAR(4000),
  REGION_ID VARCHAR(4000)
);

DROP TABLE IF EXISTS ext_address;

CREATE TABLE ext_address
(
  ADDRESS_ID VARCHAR(4000),
  ADDRESS VARCHAR(4000),
  ADDRESS2 VARCHAR(4000),
  DISTRICT VARCHAR(4000),
  CITY_ID VARCHAR(4000),
  POSTAL_CODE VARCHAR(4000)
);

DROP TABLE IF EXISTS ext_employees;

CREATE TABLE ext_employees
(
  EMPLOYEE_ID VARCHAR(4000),
  FIRST_NAME VARCHAR(4000),
  LAST_NAME VARCHAR(4000),
  POST_ID VARCHAR(4000),
  STORE_ID VARCHAR(4000)
);

DROP TABLE IF EXISTS ext_authors;

CREATE TABLE ext_authors
(
  AUTHOR_ID  VARCHAR(4000),
  AUTHOR_NAME VARCHAR(4000)
);

DROP TABLE IF EXISTS ext_books;

CREATE TABLE ext_books
(
  BOOK_ID VARCHAR(4000),
  ISBN  VARCHAR(4000),
  PUBLISHER VARCHAR(4000),
  BOOK_TITLE VARCHAR(4000),
  BOOK_AUTHOR VARCHAR(4000),
  YEAR_OF_PUBLICATION VARCHAR(4000),
  AUTHOR_ID VARCHAR(4000),
  CATEGORY_ID VARCHAR(4000),
  CATEGORY VARCHAR(4000),
  SUB_CATEGORY_ID VARCHAR(4000),
  SUB_CATEGORY VARCHAR(4000)
);

DROP TABLE IF EXISTS ext_customers;

CREATE TABLE ext_customers
(
  CUSTOMER_ID VARCHAR(4000),
  FIRST_NAME VARCHAR(4000),
  LAST_NAME VARCHAR(4000),
  GENDER VARCHAR(4000),
  DATE_OF_BIRTH VARCHAR(4000),
  ADDRESS_ID VARCHAR(4000)
);

DROP TABLE IF EXISTS ext_transaction_retail;

CREATE TABLE ext_transaction_retail
(
  SALE_ID VARCHAR(4000),
  INVOICE VARCHAR(4000),  
  STORE_ID VARCHAR(4000),
  QUANTITY VARCHAR(4000),
  PRICE  VARCHAR(4000),
  CUSTOMER_ID VARCHAR(4000),  
  INVOICE_DATE VARCHAR(4000),
  SALE_AMOUNT VARCHAR(4000),
  ADDRESS_ID VARCHAR(4000),
  EMPLOYEE_ID VARCHAR(4000),
  type_payment_id VARCHAR(4000),
  BOOK_ID VARCHAR(4000)
);