CREATE MASTER KEY;

CREATE DATABASE SCOPED CREDENTIAL AzureSqlSqrverCredentialETL
WITH IDENTITY = 'EtlAdmin',
SECRET = '';


CREATE EXTERNAL DATA SOURCE sql_ds_sa_retail
 WITH 
 ( TYPE = RDBMS,
   LOCATION = 'etlbooksalessqlserver.database.windows.net',
   DATABASE_NAME = 'SA_RETAIL',
   CREDENTIAL = AzureSqlSqrverCredentialETL 
 );
 
CREATE EXTERNAL DATA SOURCE sql_ds_sa_stock
 WITH 
 ( TYPE = RDBMS,
   LOCATION = 'etlbooksalessqlserver.database.windows.net',
   DATABASE_NAME = 'SA_STOCK',
   CREDENTIAL = AzureSqlSqrverCredentialETL 
 ); 
 
CREATE EXTERNAL TABLE SA_TYPE_PAYMENTS
(
  TYPE_PAYMENT_ID VARCHAR(4000),
  TYPE_PAYMENT VARCHAR(4000),
  INSERT_DT DATE,
  UPDATE_DT DATE
)
WITH 
(
  DATA_SOURCE = sql_ds_sa_retail
);

CREATE EXTERNAL TABLE SA_TYPE_STORES
(
  TYPE_STORE_ID VARCHAR(4000),
  TYPE_STORE VARCHAR(4000),
  INSERT_DT DATE,
  UPDATE_DT DATE
)
WITH 
(
  DATA_SOURCE = sql_ds_sa_retail
);

CREATE EXTERNAL TABLE sa_stores
(
  STORE_ID VARCHAR(4000),
  STORE_NAME VARCHAR(4000),
  STORE_TYPE_ID VARCHAR(4000),
  IS_CPROCESSED VARCHAR(1),
  INSERT_DT DATE,
  UPDATE_DT DATE
)
WITH 
(
  DATA_SOURCE = sql_ds_sa_retail
);

CREATE EXTERNAL TABLE sa_regions
(
  REGION_ID VARCHAR(4000),
  REGION_NAME VARCHAR(4000),
  INSERT_DT DATE,
  UPDATE_DT DATE
)
WITH 
(
  DATA_SOURCE = sql_ds_sa_retail
);

CREATE EXTERNAL TABLE sa_countries 
(
  COUNTRY_ID VARCHAR(4000),
  COUNTRY VARCHAR(4000),
  REGION_ID VARCHAR(4000),
  INSERT_DT DATE,
  UPDATE_DT DATE
)
WITH 
(
  DATA_SOURCE = sql_ds_sa_retail
);

CREATE EXTERNAL TABLE sa_cities 
(
  CITY_ID VARCHAR(4000),
  CITY VARCHAR(4000),
  COUNTRY_ID VARCHAR(4000),
  INSERT_DT DATE,
  UPDATE_DT DATE
)
WITH 
(
  DATA_SOURCE = sql_ds_sa_retail
);

CREATE EXTERNAL TABLE sa_address 
(
  ADDRESS_ID VARCHAR(4000),
  ADDRESS VARCHAR(4000),
  ADDRESS2 VARCHAR(4000),
  DISTRICT VARCHAR(4000),  
  CITY_ID VARCHAR(4000),
  POSTAL_CODE VARCHAR(4000),
  INSERT_DT DATE,
  UPDATE_DT DATE
)
WITH 
(
  DATA_SOURCE = sql_ds_sa_retail
);

CREATE EXTERNAL TABLE SA_POSTS 
(
  POST_ID  VARCHAR(4000),
  POST_NAME  VARCHAR(4000),
  INSERT_DT DATE,
  UPDATE_DT DATE
)
WITH 
(
  DATA_SOURCE = sql_ds_sa_retail
);

CREATE EXTERNAL TABLE sa_employees 
(
  EMPLOYEE_ID VARCHAR(4000),
  FIRST_NAME VARCHAR(4000),
  LAST_NAME VARCHAR(4000),
  POST_ID VARCHAR(4000),
  STORE_ID VARCHAR(4000),
  INSERT_DT DATE,
  UPDATE_DT DATE
)
WITH 
(
  DATA_SOURCE = sql_ds_sa_retail
);

CREATE EXTERNAL TABLE sa_customers_retail 
(
  CUSTOMER_ID VARCHAR(4000),
  FIRST_NAME VARCHAR(4000),
  LAST_NAME VARCHAR(4000),
  GENDER VARCHAR(4000),
  DATE_OF_BIRTH VARCHAR(4000), 
  ADDRESS_ID VARCHAR(4000),
  INSERT_DT DATE,
  UPDATE_DT DATE
)
WITH 
(
  DATA_SOURCE = sql_ds_sa_retail
);

CREATE EXTERNAL TABLE sa_customers_stock 
(
  CUSTOMER_ID VARCHAR(4000),
  NAME_OF_ORGANIZATION VARCHAR(4000),
  HEAD_OF_ORGANIZATION VARCHAR(4000),
  EMAIL VARCHAR(4000),
  IBAN VARCHAR(4000),
  ADDRESS_ID VARCHAR(4000),
  INSERT_DT DATE,
  UPDATE_DT DATE
)
WITH 
(
  DATA_SOURCE = sql_ds_sa_stock
);

CREATE EXTERNAL TABLE sa_books 
(
  BOOK_ID VARCHAR(4000),
  ISBN VARCHAR(4000),
  PUBLISHER VARCHAR(4000),
  BOOK_TITLE VARCHAR(4000),
  BOOK_AUTHOR VARCHAR(4000),
  YEAR_OF_PUBLICATION VARCHAR(4000),
  AUTHOR_ID VARCHAR(4000),
  CATEGORY_ID VARCHAR(4000),
  CATEGORY VARCHAR(4000),
  SUB_CATEGORY_ID VARCHAR(4000),
  SUB_CATEGORY VARCHAR(4000),
  INSERT_DT DATE,
  UPDATE_DT DATE
)
WITH 
(
  DATA_SOURCE = sql_ds_sa_retail
);

CREATE EXTERNAL TABLE sa_authors 
(
  AUTHOR_ID VARCHAR(4000),
  AUTHOR_NAME VARCHAR(4000),
  INSERT_DT DATE,
  UPDATE_DT DATE
)
WITH 
(
  DATA_SOURCE = sql_ds_sa_retail
);


