DROP TABLE if EXISTS sa_employees;

CREATE TABLE sa_employees
(
  EMPLOYEE_ID VARCHAR(4000),
  FIRST_NAME VARCHAR(4000),
  LAST_NAME VARCHAR(4000),
  POST_ID VARCHAR(4000),
  STORE_ID VARCHAR(4000),
  INSERT_DT DATE DEFAULT GETDATE(),
  UPDATE_DT DATE DEFAULT GETDATE()
);